### PR TITLE
Add pre-commit flow

### PR DESCRIPTION
**Pull request by mdeweerd**
This adds a pre-commit setup and configuration for some tools.

Helps to format files and find some potential issues.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you!

I do not consider myself a developer, I do not write code daily.
After cleaning up the repository today I could introduce markdownlint.

**Comment by szepeviktor** [comment]
... shellcheck is being used but not strictly

**Comment by szepeviktor** [comment]
🎉 Just clean up all false positive typos base on your PR.
https://github.com/szepeviktor/debian-server-tools/commit/dbd1e5d54ad67d0fd00c7278436b2a819701fd6a

Thank you.

**Comment by szepeviktor** [comment]
One more thing: https://github.com/pre-commit/pre-commit-hooks/tree/main#hooks-available
These checks are very-very interesting. I'm diving into them right now.
Thank you again.

**Comment by mdeweerd** [comment]
`pre-commit` is great to "fix" stuff locally before even making the commit.  If I want to bypass it, I just do 'pre-commit uninstall'.

I learn some things as well: I did not known shellcheck for which the pre-commit configuration does not work properly on my platform unfortunately.

I was thinking about what I can share, and I did not see any "default" `.bashrc` - I have a .bashrc and .screenrc that I use on pretty much every remote platform.  Should I just drop that in 'input' ?*.   You can find them in this gist: https://gist.github.com/07918a6a1300fa64f0faf08c7e2a1dd1 .

**Comment by szepeviktor** [comment]
There is something in https://github.com/szepeviktor/debian-server-tools/blob/master/debian-setup/packages/adduser#L66-L176
You know I am not a developer. Sometime I write libraries but not code on request, not on request from clients. Measurements and thinking what I do.

**Pull request closed without merging**
